# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CommandOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'output': 'str',
        'grunt_command_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'output': 'output',
        'grunt_command_id': 'gruntCommandId'
    }

    def __init__(self, id=None, output=None, grunt_command_id=None):  # noqa: E501
        """CommandOutput - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._output = None
        self._grunt_command_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if output is not None:
            self.output = output
        self.grunt_command_id = grunt_command_id

    @property
    def id(self):
        """Gets the id of this CommandOutput.  # noqa: E501


        :return: The id of this CommandOutput.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CommandOutput.


        :param id: The id of this CommandOutput.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def output(self):
        """Gets the output of this CommandOutput.  # noqa: E501


        :return: The output of this CommandOutput.  # noqa: E501
        :rtype: str
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this CommandOutput.


        :param output: The output of this CommandOutput.  # noqa: E501
        :type: str
        """

        self._output = output

    @property
    def grunt_command_id(self):
        """Gets the grunt_command_id of this CommandOutput.  # noqa: E501


        :return: The grunt_command_id of this CommandOutput.  # noqa: E501
        :rtype: int
        """
        return self._grunt_command_id

    @grunt_command_id.setter
    def grunt_command_id(self, grunt_command_id):
        """Sets the grunt_command_id of this CommandOutput.


        :param grunt_command_id: The grunt_command_id of this CommandOutput.  # noqa: E501
        :type: int
        """
        if grunt_command_id is None:
            raise ValueError("Invalid value for `grunt_command_id`, must not be `None`")  # noqa: E501

        self._grunt_command_id = grunt_command_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CommandOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CommandOutput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
