# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class IdentityRole(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'normalized_name': 'str',
        'concurrency_stamp': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'normalized_name': 'normalizedName',
        'concurrency_stamp': 'concurrencyStamp'
    }

    def __init__(self, id=None, name=None, normalized_name=None, concurrency_stamp=None):  # noqa: E501
        """IdentityRole - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._normalized_name = None
        self._concurrency_stamp = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if normalized_name is not None:
            self.normalized_name = normalized_name
        if concurrency_stamp is not None:
            self.concurrency_stamp = concurrency_stamp

    @property
    def id(self):
        """Gets the id of this IdentityRole.  # noqa: E501


        :return: The id of this IdentityRole.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this IdentityRole.


        :param id: The id of this IdentityRole.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this IdentityRole.  # noqa: E501


        :return: The name of this IdentityRole.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this IdentityRole.


        :param name: The name of this IdentityRole.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def normalized_name(self):
        """Gets the normalized_name of this IdentityRole.  # noqa: E501


        :return: The normalized_name of this IdentityRole.  # noqa: E501
        :rtype: str
        """
        return self._normalized_name

    @normalized_name.setter
    def normalized_name(self, normalized_name):
        """Sets the normalized_name of this IdentityRole.


        :param normalized_name: The normalized_name of this IdentityRole.  # noqa: E501
        :type: str
        """

        self._normalized_name = normalized_name

    @property
    def concurrency_stamp(self):
        """Gets the concurrency_stamp of this IdentityRole.  # noqa: E501


        :return: The concurrency_stamp of this IdentityRole.  # noqa: E501
        :rtype: str
        """
        return self._concurrency_stamp

    @concurrency_stamp.setter
    def concurrency_stamp(self, concurrency_stamp):
        """Sets the concurrency_stamp of this IdentityRole.


        :param concurrency_stamp: The concurrency_stamp of this IdentityRole.  # noqa: E501
        :type: str
        """

        self._concurrency_stamp = concurrency_stamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IdentityRole, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IdentityRole):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
