# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.theme_api_api import ThemeApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestThemeApiApi(unittest.TestCase):
    """ThemeApiApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.theme_api_api.ThemeApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_theme(self):
        """Test case for create_theme

        """
        pass

    def test_delete_theme(self):
        """Test case for delete_theme

        """
        pass

    def test_edit_theme(self):
        """Test case for edit_theme

        """
        pass

    def test_get_theme(self):
        """Test case for get_theme

        """
        pass

    def test_get_themes(self):
        """Test case for get_themes

        """
        pass


if __name__ == '__main__':
    unittest.main()
