# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.reference_assembly import ReferenceAssembly  # noqa: E501
from swagger_client.rest import ApiException


class TestReferenceAssembly(unittest.TestCase):
    """ReferenceAssembly unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReferenceAssembly(self):
        """Test ReferenceAssembly"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.reference_assembly.ReferenceAssembly()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
