# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.profile_api_api import ProfileApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProfileApiApi(unittest.TestCase):
    """ProfileApiApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.profile_api_api.ProfileApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_http_profile(self):
        """Test case for create_http_profile

        """
        pass

    def test_create_profile(self):
        """Test case for create_profile

        """
        pass

    def test_delete_http_profile(self):
        """Test case for delete_http_profile

        """
        pass

    def test_delete_profile(self):
        """Test case for delete_profile

        """
        pass

    def test_edit_http_profile(self):
        """Test case for edit_http_profile

        """
        pass

    def test_edit_profile(self):
        """Test case for edit_profile

        """
        pass

    def test_get_http_profile(self):
        """Test case for get_http_profile

        """
        pass

    def test_get_http_profiles(self):
        """Test case for get_http_profiles

        """
        pass

    def test_get_profile(self):
        """Test case for get_profile

        """
        pass

    def test_get_profiles(self):
        """Test case for get_profiles

        """
        pass


if __name__ == '__main__':
    unittest.main()
