# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.http_profile import HttpProfile  # noqa: E501
from swagger_client.rest import ApiException


class TestHttpProfile(unittest.TestCase):
    """HttpProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHttpProfile(self):
        """Test HttpProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.http_profile.HttpProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
