# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.target_indicator import TargetIndicator  # noqa: E501
from swagger_client.rest import ApiException


class TestTargetIndicator(unittest.TestCase):
    """TargetIndicator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTargetIndicator(self):
        """Test TargetIndicator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.target_indicator.TargetIndicator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
