# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.implant_language import ImplantLanguage  # noqa: E501
from swagger_client.rest import ApiException


class TestImplantLanguage(unittest.TestCase):
    """ImplantLanguage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImplantLanguage(self):
        """Test ImplantLanguage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.implant_language.ImplantLanguage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
