# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reference_assembly_api_api import ReferenceAssemblyApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReferenceAssemblyApiApi(unittest.TestCase):
    """ReferenceAssemblyApiApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.reference_assembly_api_api.ReferenceAssemblyApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_reference_assembly(self):
        """Test case for create_reference_assembly

        """
        pass

    def test_delete_reference_assembly(self):
        """Test case for delete_reference_assembly

        """
        pass

    def test_edit_reference_assembly(self):
        """Test case for edit_reference_assembly

        """
        pass

    def test_get_reference_assemblies(self):
        """Test case for get_reference_assemblies

        """
        pass

    def test_get_reference_assembly(self):
        """Test case for get_reference_assembly

        """
        pass


if __name__ == '__main__':
    unittest.main()
