# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.event_api_api import EventApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEventApiApi(unittest.TestCase):
    """EventApiApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.event_api_api.EventApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_download_event(self):
        """Test case for create_download_event

        """
        pass

    def test_create_event(self):
        """Test case for create_event

        """
        pass

    def test_get_download_content(self):
        """Test case for get_download_content

        """
        pass

    def test_get_download_event(self):
        """Test case for get_download_event

        """
        pass

    def test_get_event(self):
        """Test case for get_event

        """
        pass

    def test_get_event_time(self):
        """Test case for get_event_time

        """
        pass

    def test_get_events(self):
        """Test case for get_events

        """
        pass

    def test_get_events_after(self):
        """Test case for get_events_after

        """
        pass

    def test_get_events_range(self):
        """Test case for get_events_range

        """
        pass


if __name__ == '__main__':
    unittest.main()
