# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.regsvr32_launcher import Regsvr32Launcher  # noqa: E501
from swagger_client.rest import ApiException


class TestRegsvr32Launcher(unittest.TestCase):
    """Regsvr32Launcher unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegsvr32Launcher(self):
        """Test Regsvr32Launcher"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.regsvr32_launcher.Regsvr32Launcher()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
