# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.launcher_api_api import LauncherApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLauncherApiApi(unittest.TestCase):
    """LauncherApiApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.launcher_api_api.LauncherApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_edit_binary_launcher(self):
        """Test case for edit_binary_launcher

        """
        pass

    def test_edit_cscript_launcher(self):
        """Test case for edit_cscript_launcher

        """
        pass

    def test_edit_install_util_launcher(self):
        """Test case for edit_install_util_launcher

        """
        pass

    def test_edit_ms_build_launcher(self):
        """Test case for edit_ms_build_launcher

        """
        pass

    def test_edit_mshta_launcher(self):
        """Test case for edit_mshta_launcher

        """
        pass

    def test_edit_power_shell_launcher(self):
        """Test case for edit_power_shell_launcher

        """
        pass

    def test_edit_regsvr32_launcher(self):
        """Test case for edit_regsvr32_launcher

        """
        pass

    def test_edit_shell_code_launcher(self):
        """Test case for edit_shell_code_launcher

        """
        pass

    def test_edit_wmic_launcher(self):
        """Test case for edit_wmic_launcher

        """
        pass

    def test_edit_wscript_launcher(self):
        """Test case for edit_wscript_launcher

        """
        pass

    def test_generate_binary_hosted_launcher(self):
        """Test case for generate_binary_hosted_launcher

        """
        pass

    def test_generate_binary_launcher(self):
        """Test case for generate_binary_launcher

        """
        pass

    def test_generate_cscript_hosted_file_launcher(self):
        """Test case for generate_cscript_hosted_file_launcher

        """
        pass

    def test_generate_cscript_launcher(self):
        """Test case for generate_cscript_launcher

        """
        pass

    def test_generate_install_util_hosted_file_launcher(self):
        """Test case for generate_install_util_hosted_file_launcher

        """
        pass

    def test_generate_install_util_launcher(self):
        """Test case for generate_install_util_launcher

        """
        pass

    def test_generate_ms_build_hosted_file_launcher(self):
        """Test case for generate_ms_build_hosted_file_launcher

        """
        pass

    def test_generate_ms_build_launcher(self):
        """Test case for generate_ms_build_launcher

        """
        pass

    def test_generate_mshta_hosted_file_launcher(self):
        """Test case for generate_mshta_hosted_file_launcher

        """
        pass

    def test_generate_mshta_launcher(self):
        """Test case for generate_mshta_launcher

        """
        pass

    def test_generate_power_shell_hosted_file_launcher(self):
        """Test case for generate_power_shell_hosted_file_launcher

        """
        pass

    def test_generate_power_shell_launcher(self):
        """Test case for generate_power_shell_launcher

        """
        pass

    def test_generate_regsvr32_hosted_file_launcher(self):
        """Test case for generate_regsvr32_hosted_file_launcher

        """
        pass

    def test_generate_regsvr32_launcher(self):
        """Test case for generate_regsvr32_launcher

        """
        pass

    def test_generate_shell_code_hosted_launcher(self):
        """Test case for generate_shell_code_hosted_launcher

        """
        pass

    def test_generate_shell_code_launcher(self):
        """Test case for generate_shell_code_launcher

        """
        pass

    def test_generate_wmic_hosted_file_launcher(self):
        """Test case for generate_wmic_hosted_file_launcher

        """
        pass

    def test_generate_wmic_launcher(self):
        """Test case for generate_wmic_launcher

        """
        pass

    def test_generate_wscript_hosted_file_launcher(self):
        """Test case for generate_wscript_hosted_file_launcher

        """
        pass

    def test_generate_wscript_launcher(self):
        """Test case for generate_wscript_launcher

        """
        pass

    def test_get_binary_launcher(self):
        """Test case for get_binary_launcher

        """
        pass

    def test_get_cscript_launcher(self):
        """Test case for get_cscript_launcher

        """
        pass

    def test_get_install_util_launcher(self):
        """Test case for get_install_util_launcher

        """
        pass

    def test_get_launchers(self):
        """Test case for get_launchers

        """
        pass

    def test_get_ms_build_launcher(self):
        """Test case for get_ms_build_launcher

        """
        pass

    def test_get_mshta_launcher(self):
        """Test case for get_mshta_launcher

        """
        pass

    def test_get_power_shell_launcher(self):
        """Test case for get_power_shell_launcher

        """
        pass

    def test_get_regsvr32_launcher(self):
        """Test case for get_regsvr32_launcher

        """
        pass

    def test_get_shell_code_launcher(self):
        """Test case for get_shell_code_launcher

        """
        pass

    def test_get_wmic_launcher(self):
        """Test case for get_wmic_launcher

        """
        pass

    def test_get_wscript_launcher(self):
        """Test case for get_wscript_launcher

        """
        pass


if __name__ == '__main__':
    unittest.main()
