# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.command_output_api_api import CommandOutputApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommandOutputApiApi(unittest.TestCase):
    """CommandOutputApiApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.command_output_api_api.CommandOutputApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_append_command_output(self):
        """Test case for append_command_output

        """
        pass

    def test_create_command_output(self):
        """Test case for create_command_output

        """
        pass

    def test_delete_command_output(self):
        """Test case for delete_command_output

        """
        pass

    def test_edit_command_output(self):
        """Test case for edit_command_output

        """
        pass

    def test_get_command_output(self):
        """Test case for get_command_output

        """
        pass

    def test_get_command_outputs(self):
        """Test case for get_command_outputs

        """
        pass


if __name__ == '__main__':
    unittest.main()
