# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.credential_api_api import CredentialApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCredentialApiApi(unittest.TestCase):
    """CredentialApiApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.credential_api_api.CredentialApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_hash_credential(self):
        """Test case for create_hash_credential

        """
        pass

    def test_create_password_credential(self):
        """Test case for create_password_credential

        """
        pass

    def test_create_ticket_credential(self):
        """Test case for create_ticket_credential

        """
        pass

    def test_delete_credential(self):
        """Test case for delete_credential

        """
        pass

    def test_edit_hash_credential(self):
        """Test case for edit_hash_credential

        """
        pass

    def test_edit_password_credential(self):
        """Test case for edit_password_credential

        """
        pass

    def test_edit_ticket_credential(self):
        """Test case for edit_ticket_credential

        """
        pass

    def test_get_credential(self):
        """Test case for get_credential

        """
        pass

    def test_get_credentials(self):
        """Test case for get_credentials

        """
        pass

    def test_get_hash_credential(self):
        """Test case for get_hash_credential

        """
        pass

    def test_get_hash_credentials(self):
        """Test case for get_hash_credentials

        """
        pass

    def test_get_password_credential(self):
        """Test case for get_password_credential

        """
        pass

    def test_get_password_credentials(self):
        """Test case for get_password_credentials

        """
        pass

    def test_get_ticket_credential(self):
        """Test case for get_ticket_credential

        """
        pass

    def test_get_ticket_credentials(self):
        """Test case for get_ticket_credentials

        """
        pass


if __name__ == '__main__':
    unittest.main()
