# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reference_source_library_api_api import ReferenceSourceLibraryApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReferenceSourceLibraryApiApi(unittest.TestCase):
    """ReferenceSourceLibraryApiApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.reference_source_library_api_api.ReferenceSourceLibraryApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_reference_source_library(self):
        """Test case for create_reference_source_library

        """
        pass

    def test_delete_reference_source_library(self):
        """Test case for delete_reference_source_library

        """
        pass

    def test_edit_reference_source_library(self):
        """Test case for edit_reference_source_library

        """
        pass

    def test_get_reference_source_libraries(self):
        """Test case for get_reference_source_libraries

        """
        pass

    def test_get_reference_source_library(self):
        """Test case for get_reference_source_library

        """
        pass


if __name__ == '__main__':
    unittest.main()
