# coding: utf-8

"""
    Covenant API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.grunt_task_api_api import GruntTaskApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGruntTaskApiApi(unittest.TestCase):
    """GruntTaskApiApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.grunt_task_api_api.GruntTaskApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_grunt_task(self):
        """Test case for create_grunt_task

        """
        pass

    def test_delete_grunt_task(self):
        """Test case for delete_grunt_task

        """
        pass

    def test_edit_grunt_task(self):
        """Test case for edit_grunt_task

        """
        pass

    def test_get_grunt_task(self):
        """Test case for get_grunt_task

        """
        pass

    def test_get_grunt_tasks(self):
        """Test case for get_grunt_tasks

        """
        pass


if __name__ == '__main__':
    unittest.main()
